export const CATEGORY_CONTROL = {
  ACCESIBILITY: 'ACCESIBILITY',
  CONTENT: 'CONTENT',
  CUSTOMIZATION: 'CUSTOMIZATION',
  DATA: 'DATA',
  FUNCTIONS: 'FUNCTIONS',
  MODIFIERS: 'MODIFIERS',
  TESTING: 'TESTING',
};
