import { BarChartErrorMessages } from '../errorMessages/barChartErrorMessages';

export const BarChartErrors = {
  // Axis & Scale Errors
  BAR_CHART_AXIS_INSUFFICIENT_TICKS: 'BAR_CHART_AXIS_INSUFFICIENT_TICKS',
  BAR_CHART_AXIS_INVALID_SCALE: 'BAR_CHART_AXIS_INVALID_SCALE',

  // Distribution Errors
  BAR_CHART_DISTRIBUTION_INSUFFICIENT_SPACE: 'BAR_CHART_DISTRIBUTION_INSUFFICIENT_SPACE',
  BAR_CHART_DISTRIBUTION_INVALID_GAP: 'BAR_CHART_DISTRIBUTION_INVALID_GAP',
  BAR_CHART_DISTRIBUTION_OVERLAP: 'BAR_CHART_DISTRIBUTION_OVERLAP',

  // Data Validation Errors
  BAR_CHART_EMPTY_DATA: 'BAR_CHART_EMPTY_DATA',
  BAR_CHART_INSUFFICIENT_SPACE_HEIGHT: 'BAR_CHART_INSUFFICIENT_SPACE_HEIGHT',
  BAR_CHART_INSUFFICIENT_SPACE_WIDTH: 'BAR_CHART_INSUFFICIENT_SPACE_WIDTH',
  BAR_CHART_INVALID_VALUE: 'BAR_CHART_INVALID_VALUE',
  BAR_CHART_NEGATIVE_VALUE: 'BAR_CHART_NEGATIVE_VALUE',
  BAR_CHART_NO_DATA: 'BAR_CHART_NO_DATA',
  BAR_CHART_OVERLAP: 'BAR_CHART_OVERLAP',

  // Separator Errors
  BAR_CHART_SEPARATOR_X_OUT_OF_RANGE: 'BAR_CHART_SEPARATOR_X_OUT_OF_RANGE',
  BAR_CHART_SEPARATOR_Y_OUT_OF_RANGE: 'BAR_CHART_SEPARATOR_Y_OUT_OF_RANGE',

  // Stack Errors
  BAR_CHART_STACK_INVALID: 'BAR_CHART_STACK_INVALID',
  BAR_CHART_STACK_MISSING_VALUES: 'BAR_CHART_STACK_MISSING_VALUES',
} as const;

export const BarChartErrorsRecord = Object.entries(BarChartErrorMessages).reduce(
  (acc, [key, message]) => {
    acc[key as keyof typeof BarChartErrorMessages] = new Error(message);
    return acc;
  },
  {} as Record<keyof typeof BarChartErrorMessages, Error>
);
