import { LineChartErrorMessages } from '../errorMessages/lineChartErrorMessages';

export const LineChartErrors = {
  // LineChart Context Errors
  LINE_CHART_INVALID_CANVAS: 'LINE_CHART_INVALID_CANVAS',
  LINE_CHART_NO_DATA: 'LINE_CHART_NO_DATA',

  // LineChart Path Errors
  LINE_CHART_PATH_ALL_VALUES_NULL: 'LINE_CHART_PATH_ALL_VALUES_NULL',
  LINE_CHART_PATH_INSUFFICIENT_POINTS: 'LINE_CHART_PATH_INSUFFICIENT_POINTS',
  LINE_CHART_PATH_INVALID_DATAKEY: 'LINE_CHART_PATH_INVALID_DATAKEY',

  // LineChart Projection Errors
  LINE_CHART_PROJECTION_INVALID_BOUNDS: 'LINE_CHART_PROJECTION_INVALID_BOUNDS',
  LINE_CHART_PROJECTION_LOWER_X_OUT_OF_RANGE: 'LINE_CHART_PROJECTION_LOWER_X_OUT_OF_RANGE',
  LINE_CHART_PROJECTION_LOWER_Y_OUT_OF_RANGE: 'LINE_CHART_PROJECTION_LOWER_Y_OUT_OF_RANGE',
  LINE_CHART_PROJECTION_UPPER_X_OUT_OF_RANGE: 'LINE_CHART_PROJECTION_UPPER_X_OUT_OF_RANGE',
  LINE_CHART_PROJECTION_UPPER_Y_OUT_OF_RANGE: 'LINE_CHART_PROJECTION_UPPER_Y_OUT_OF_RANGE',

  // LineChart Separator Errors
  LINE_CHART_SEPARATOR_INVALID_COORDINATES: 'LINE_CHART_SEPARATOR_INVALID_COORDINATES',
  LINE_CHART_SEPARATOR_INVALID_X_BREAK_AXIS: 'LINE_CHART_SEPARATOR_INVALID_X_BREAK_AXIS',
  LINE_CHART_SEPARATOR_INVALID_Y_BREAK_AXIS: 'LINE_CHART_SEPARATOR_INVALID_Y_BREAK_AXIS',
  LINE_CHART_SEPARATOR_X_OUT_OF_RANGE: 'LINE_CHART_SEPARATOR_X_OUT_OF_RANGE',
  LINE_CHART_SEPARATOR_Y_OUT_OF_RANGE: 'LINE_CHART_SEPARATOR_Y_OUT_OF_RANGE',
  LINE_CHART_SINGLE_POINT: 'LINE_CHART_SINGLE_POINT',

  // LineChart Axis Errors
  LINE_CHART_X_AXIS_IDENTICAL_VALUES: 'LINE_CHART_X_AXIS_IDENTICAL_VALUES',
  LINE_CHART_X_AXIS_INSUFFICIENT_TICKS: 'LINE_CHART_X_AXIS_INSUFFICIENT_TICKS',
  LINE_CHART_X_AXIS_ZERO_LENGTH: 'LINE_CHART_X_AXIS_ZERO_LENGTH',
  LINE_CHART_Y_AXIS_IDENTICAL_VALUES: 'LINE_CHART_Y_AXIS_IDENTICAL_VALUES',
  LINE_CHART_Y_AXIS_INSUFFICIENT_TICKS: 'LINE_CHART_Y_AXIS_INSUFFICIENT_TICKS',
  LINE_CHART_Y_AXIS_ZERO_LENGTH: 'LINE_CHART_Y_AXIS_ZERO_LENGTH',
} as const;

export const LineChartErrorsRecord = Object.entries(LineChartErrorMessages).reduce(
  (acc, [key, message]) => {
    acc[key as keyof typeof LineChartErrorMessages] = new Error(message);
    return acc;
  },
  {} as Record<keyof typeof LineChartErrorMessages, Error>
);
